#!/bin/bash
# AVATARARTS Knowledge Base Initialization Script

echo "==========================================="
echo "AVATARARTS Knowledge Base System"
echo "==========================================="
echo ""
echo "System Location: ~/AutoTagger/v3-dev/"
echo "Database: ~/AutoTagger/v3-dev/knowledge_base.db"
echo ""
echo "Available Tools:"
echo "1. save_knowledge.sh - Save knowledge entries"
echo "2. capture_conversation.py - Capture conversation data"
echo "3. save_knowledge_to_db.py - Direct database access"
echo "4. kb_aliases.sh - Shell aliases for quick access"
echo ""
echo "To use the system, add these aliases to your shell:"
echo "source ~/AutoTagger/v3-dev/kb_aliases.sh"
echo ""
echo "Then you can use:"
echo "- save-kb : Save/search knowledge entries"
echo "- capture-kb : Capture conversation data"
echo "- quick-save-kb : Save clipboard content"
echo ""
echo "==========================================="
echo "System Status: Active and Ready"
echo "==========================================="